"""add 2FA fields to user

Revision ID: e0d76843cf0d
Revises: 20260509_0001
Create Date: 2026-05-09 23:13:08.563055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d76843cf0d'
down_revision = '20260509_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_fa_enabled', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('two_fa_enabled')

    # ### end Alembic commands ###
